### ISSUE TITLE
Player can jump after touching moveable platforms

### ISSUE THREAD

**Issue by CamYuan** [SamBumgardner/csc-303-platformer#8]
Tested on CheezitBandit's Collision Branch.

After jumping onto a moveable platform, if a player walks off, the player.onGround remains true and is able to jump mid fall. I believe this can be fixed by adding an else statement in the Player class around line 233.

if (isTouching(FlxObject.DOWN))
		{
			onGround = true;
		} else {
			onGround = false;
		}

**Comment by CheezitBandit** [comment]
This is probably something that should be addressed on the player branch. I've been trying to make all of my changes outside of that class, to avoid as many merge conflicts as possible.

**Comment by SamBumgardner** [comment]
We can check if this is still an issue after you merge the newest version of master (with the updated player class) into your collision branch. If it is, we'll take care of it before merging in your branch.

**Comment by CheezitBandit** [comment]
Just merged the latest version of master with the collision branch. This issue has been addressed by someone in the player class and is no longer a problem.
